name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18, 20, 22]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: gemini-flow/package-lock.json
    
    - name: Install dependencies
      working-directory: ./gemini-flow
      run: npm ci
    
    - name: Run type checking
      working-directory: ./gemini-flow
      run: npm run typecheck
    
    - name: Run linting
      working-directory: ./gemini-flow
      run: npm run lint
    
    - name: Run unit tests
      working-directory: ./gemini-flow
      run: npm run test:unit
    
    - name: Run integration tests
      working-directory: ./gemini-flow
      run: npm run test:integration
    
    - name: Build project
      working-directory: ./gemini-flow
      run: npm run build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts-node-${{ matrix.node-version }}
        path: gemini-flow/dist/
        retention-days: 7